name: task-manager

services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'task-manager'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'task-manager'
    ports:
      - '5432:5432'
    volumes:
      - database-pg:/var/lib/postgresql/data